name: Greet the bonhomme

on:
  issues:
    types: [opened, closed]  

jobs:
  greetings:
    if: ${{ github.event.action == 'opened' }}
    name: Print the greeting
    runs-on: ubuntu-latest
    steps:
      - name: Echo Action
        run: echo 'Salut ${{github.event.issue.user.login}}!'
  goodbye:
    if: ${{ github.event.action == 'closed' }}
    name: Print the goodbye
    runs-on: ubuntu-latest
    steps:
      - name: Echo Action
        run: echo 'Au revoir  ${{github.event.issue.user.login}}!'
